name: Build
on:
  workflow_dispatch: {}
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linux-cuda:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone latest llama.cpp
        run: git clone https://github.com/ggerganov/llama.cpp --depth=1

      - name: Pull `llama-server` image
        run: docker pull ghcr.io/ggml-org/llama.cpp:server-cuda

      - name: Create llama-server container
        run: docker create --name llama-server ghcr.io/ggml-org/llama.cpp:server-cuda

      - name: Copy build artifacts from container
        run: docker cp llama-server:/app .

      - name: Copy CUDA runtime from container
        run: |
          CUDA_VERSION=$(docker run --rm --entrypoint "" ghcr.io/ggml-org/llama.cpp:server-cuda \
              bash -c "ls /usr/local | grep '^cuda-[0-9]\+\.[0-9]\+$' | sort -V | tail -n1 | sed 's/cuda-//'")

          CUDA_MAJOR_VERSION=${CUDA_VERSION%%.*}

          docker cp -L llama-server:/usr/local/cuda-$CUDA_VERSION/targets/x86_64-linux/lib/libcudart.so.$CUDA_MAJOR_VERSION app/.
          docker cp -L llama-server:/usr/local/cuda-$CUDA_VERSION/targets/x86_64-linux/lib/libcublas.so.$CUDA_MAJOR_VERSION app/.
          docker cp -L llama-server:/usr/local/cuda-$CUDA_VERSION/targets/x86_64-linux/lib/libcublasLt.so.$CUDA_MAJOR_VERSION app/.

      - name: Set $ORIGIN as RPATH for `llama-server` and shared libraries
        run: |
          patchelf --set-rpath '$ORIGIN' app/llama-server
          patchelf --set-rpath '$ORIGIN' app/*.so

      - name: Pack build artifacts
        run: |
          cp llama.cpp/LICENSE app/.
          cd app
          zip -r ../llama-server-linux-x64-cuda.zip *

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: llama-server-linux-x64-cuda.zip
          name: llama-server-linux-x64-cuda
